# Generated by Django 5.2.3 on 2025-06-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professsional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Social')),
                ('profession', models.CharField(max_length=100, verbose_name='Profissão')),
                ('address', models.CharField(max_length=200, verbose_name='Endereço')),
                ('contact', models.CharField(max_length=100, verbose_name='Contato')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
        ),
    ]
