# Generated by Django 5.2.3 on 2025-06-28 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Professsional',
            new_name='Professional',
        ),
    ]
