# Generated by Django 5.2.3 on 2025-06-28 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0002_rename_professsional_professional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Data da Consulta')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='professionals.professional')),
            ],
        ),
    ]
